In [1]:
import sys
!{sys.executable} -m pip install numpy pandas scikit-learn

Requirement already satisfied: numpy in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (2.0.2)
Requirement already satisfied: pandas in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (2.2.3)
Requirement already satisfied: scikit-learn in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (1.7.1)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2025.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\appdata\roaming\python\python310\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2025.1)
Requirement already satisfied: scipy>=1.8.0 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\roaming\python\python310\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 23.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import numpy as np

In [3]:
world_df= pd.read_csv("yield_df.csv")
sl_df= world_df[world_df["Area"]=="Sri Lanka"]
print(sl_df.shape)
print(sl_df.columns)

(184, 8)
Index(['Unnamed: 0', 'Area', 'Item', 'Year', 'hg/ha_yield',
       'average_rain_fall_mm_per_year', 'pesticides_tonnes', 'avg_temp'],
      dtype='object')

In [4]:
sl_df["kg/ha_yeild"]= sl_df["hg/ha_yield"]/10

print(sl_df.columns)

Index(['Unnamed: 0', 'Area', 'Item', 'Year', 'hg/ha_yield',
       'average_rain_fall_mm_per_year', 'pesticides_tonnes', 'avg_temp',
       'kg/ha_yeild'],
      dtype='object')

C:\Users\User\AppData\Local\Temp\ipykernel_31796\1241168035.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sl_df["kg/ha_yeild"]= sl_df["hg/ha_yield"]/10

In [5]:
print(sl_df["Item"].unique())
print(sl_df["Year"].min(), sl_df["Year"].max())
print(sl_df.head(10))

['Cassava' 'Maize' 'Plantains and others' 'Potatoes' 'Rice, paddy'
 'Sorghum' 'Soybeans' 'Sweet potatoes']
1990 2013
       Unnamed: 0       Area                  Item  Year  hg/ha_yield  \
25682       25682  Sri Lanka               Cassava  1990        87717
25683       25683  Sri Lanka                 Maize  1990        11227
25684       25684  Sri Lanka  Plantains and others  1990       140381
25685       25685  Sri Lanka              Potatoes  1990       110520
25686       25686  Sri Lanka           Rice, paddy  1990        30643
25687       25687  Sri Lanka               Sorghum  1990         7143
25688       25688  Sri Lanka              Soybeans  1990         8040
25689       25689  Sri Lanka        Sweet potatoes  1990        64750
25690       25690  Sri Lanka               Cassava  1991        92373
25691       25691  Sri Lanka                 Maize  1991        11916

       average_rain_fall_mm_per_year  pesticides_tonnes  avg_temp  kg/ha_yeild
25682                         1712.0            1571.33     26.53       8771.7
25683                         1712.0            1571.33     26.53       1122.7
25684                         1712.0            1571.33     26.53      14038.1
25685                         1712.0            1571.33     26.53      11052.0
25686                         1712.0            1571.33     26.53       3064.3
25687                         1712.0            1571.33     26.53        714.3
25688                         1712.0            1571.33     26.53        804.0
25689                         1712.0            1571.33     26.53       6475.0
25690                         1712.0            1409.15     26.53       9237.3
25691                         1712.0            1409.15     26.53       1191.6

In [6]:
sl_df= sl_df.drop(columns=["hg/ha_yield"])

In [7]:
sl_df= sl_df.rename(columns={"Unnamed: 0":"id"})
sl_df.head(3)
sl_df.shape

(184, 8)

In [8]:
# How many rows do you have?
print(sl_df.shape)

# What crops are in the dataset?
print(sl_df["Item"].unique())

# What year range?
print(sl_df["Year"].min(), "→", sl_df["Year"].max())

# Any missing values?
print(sl_df.isnull().sum())

# Basic statistics
print(sl_df.describe())

(184, 8)
['Cassava' 'Maize' 'Plantains and others' 'Potatoes' 'Rice, paddy'
 'Sorghum' 'Soybeans' 'Sweet potatoes']
1990 → 2013
id                               0
Area                             0
Item                             0
Year                             0
average_rain_fall_mm_per_year    0
pesticides_tonnes                0
avg_temp                         0
kg/ha_yeild                      0
dtype: int64
                 id         Year  average_rain_fall_mm_per_year  \
count    184.000000   184.000000                          184.0
mean   25773.500000  2001.434783                         1712.0
std       53.260367     7.083120                            0.0
min    25682.000000  1990.000000                         1712.0
25%    25727.750000  1995.000000                         1712.0
50%    25773.500000  2001.000000                         1712.0
75%    25819.250000  2008.000000                         1712.0
max    25865.000000  2013.000000                         1712.0

       pesticides_tonnes    avg_temp   kg/ha_yeild
count         184.000000  184.000000    184.000000
mean         1575.835217   26.603913   6096.598370
std           252.574802    0.217622   4754.020036
min          1112.800000   26.260000    615.400000
25%          1409.150000   26.420000   1276.775000
50%          1654.410000   26.590000   5046.850000
75%          1742.410000   26.730000  10653.425000
max          2144.310000   27.130000  15526.900000

In [9]:
# Check rainfall issue
print(sl_df["average_rain_fall_mm_per_year"].nunique())
# If this prints 1 — confirmed useless column

# Also check the id column — probably useless too
print(sl_df["id"].nunique())

# Look at yield range per crop — important
print(sl_df.groupby("Item")["kg/ha_yeild"].agg(["mean", "min", "max"]))

1
184
                              mean      min      max
Item
Cassava                9706.534783   8433.0  12652.7
Maize                  1619.552174    969.5   3418.7
Plantains and others  11960.143478  10325.0  14038.1
Potatoes              12956.004348  10277.3  15526.9
Rice, paddy            3452.773913   2993.3   4055.8
Sorghum                 917.752174    615.4   1422.7
Soybeans               1274.582609    804.0   2404.8
Sweet potatoes         6885.443478   6037.9   9300.2

In [10]:
sl_df= sl_df.drop(columns=["average_rain_fall_mm_per_year"])
sl_df.head(3)

,id,Area,Item,Year,pesticides_tonnes,avg_temp,kg/ha_yeild
25682,25682,Sri Lanka,Cassava,1990,1571.33,26.53,8771.7
25683,25683,Sri Lanka,Maize,1990,1571.33,26.53,1122.7
25684,25684,Sri Lanka,Plantains and others,1990,1571.33,26.53,14038.1

In [11]:
#sl_df= sl_df.drop(columns=["Area"])
sl_df.columns
sl_df.head(3)

,id,Area,Item,Year,pesticides_tonnes,avg_temp,kg/ha_yeild
25682,25682,Sri Lanka,Cassava,1990,1571.33,26.53,8771.7
25683,25683,Sri Lanka,Maize,1990,1571.33,26.53,1122.7
25684,25684,Sri Lanka,Plantains and others,1990,1571.33,26.53,14038.1

In [12]:
sl_df.head(2)

,id,Area,Item,Year,pesticides_tonnes,avg_temp,kg/ha_yeild
25682,25682,Sri Lanka,Cassava,1990,1571.33,26.53,8771.7
25683,25683,Sri Lanka,Maize,1990,1571.33,26.53,1122.7

In [13]:

sl_df = pd.get_dummies(sl_df, columns=["Item"], dtype=int)
print(sl_df.columns)

Index(['id', 'Area', 'Year', 'pesticides_tonnes', 'avg_temp', 'kg/ha_yeild',
       'Item_Cassava', 'Item_Maize', 'Item_Plantains and others',
       'Item_Potatoes', 'Item_Rice, paddy', 'Item_Sorghum', 'Item_Soybeans',
       'Item_Sweet potatoes'],
      dtype='object')

In [14]:
sl_df.head(2)

,id,Area,Year,pesticides_tonnes,avg_temp,kg/ha_yeild,Item_Cassava,Item_Maize,Item_Plantains and others,Item_Potatoes,"Item_Rice, paddy",Item_Sorghum,Item_Soybeans,Item_Sweet potatoes
25682,25682,Sri Lanka,1990,1571.33,26.53,8771.7,1,0,0,0,0,0,0,0
25683,25683,Sri Lanka,1990,1571.33,26.53,1122.7,0,1,0,0,0,0,0,0